env:
  CIRRUS_CLONE_DEPTH: 1

freebsd_12_task:
  freebsd_instance:
    image_family: freebsd-12-1
    cpu: 8
    memory: 8G
  install_script:
    - ASSUME_ALWAYS_YES=yes pkg bootstrap -f ;
    - pkg install -y bash curl cyrus-sasl git glib gmake gnutls gsed
          nettle perl5 pixman pkgconf png usbredir
  script:
    - mkdir build
    - cd build
    - ../configure --enable-werror || { cat config.log; exit 1; }
    - gmake -j$(sysctl -n hw.ncpu)
    - gmake -j$(sysctl -n hw.ncpu) check

macos_task:
  osx_instance:
    image: catalina-base
  install_script:
    - brew install pkg-config python gnu-sed glib pixman make sdl2 bash
  script:
    - mkdir build
    - cd build
    - ../configure --python=/usr/local/bin/python3 --enable-werror
                   --extra-cflags='-Wno-error=deprecated-declarations'
                   || { cat config.log; exit 1; }
    - gmake -j$(sysctl -n hw.ncpu)
    - gmake check

macos_xcode_task:
  osx_instance:
    # this is an alias for the latest Xcode
    image: catalina-xcode
  install_script:
    - brew install pkg-config gnu-sed glib pixman make sdl2 bash
  script:
    - mkdir build
    - cd build
    - ../configure --extra-cflags='-Wno-error=deprecated-declarations'
                   --enable-werror --cc=clang || { cat config.log; exit 1; }
    - gmake -j$(sysctl -n hw.ncpu)
    - gmake check

windows_msys2_task:
  windows_container:
    image: cirrusci/windowsservercore:cmake
    os_version: 2019
    cpu: 8
    memory: 8G
  env:
    MSYS: winsymlinks:nativestrict
    MSYSTEM: MINGW64
    CHERE_INVOKING: 1
  printenv_script:
    - C:\tools\msys64\usr\bin\bash.exe -lc 'printenv'
  install_script:
    - C:\tools\msys64\usr\bin\bash.exe -lc "cd /c/tools &&
        curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
    - C:\tools\msys64\usr\bin\bash.exe -lc "cd /c/tools &&
        curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
    - C:\tools\msys64\usr\bin\bash.exe -lc "cd /c/tools &&
        pacman -U --noconfirm msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
    - C:\tools\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Sy"
    - C:\tools\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S --needed
        bash pacman pacman-mirrors msys2-runtime"
    - taskkill /F /IM gpg-agent.exe
    - C:\tools\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Su"
    - C:\tools\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S --needed
        base-devel
        git
        mingw-w64-x86_64-python
        mingw-w64-x86_64-python-setuptools
        mingw-w64-x86_64-toolchain
        mingw-w64-x86_64-capstone
        mingw-w64-x86_64-SDL2
        mingw-w64-x86_64-SDL2_image
        mingw-w64-x86_64-gtk3
        mingw-w64-x86_64-glib2
        mingw-w64-x86_64-ninja
        mingw-w64-x86_64-make
        mingw-w64-x86_64-lzo2
        mingw-w64-x86_64-zstd
        mingw-w64-x86_64-libjpeg-turbo
        mingw-w64-x86_64-pixman
        mingw-w64-x86_64-libgcrypt
        mingw-w64-x86_64-libpng
        mingw-w64-x86_64-libssh
        mingw-w64-x86_64-libxml2
        mingw-w64-x86_64-snappy
        mingw-w64-x86_64-libusb
        mingw-w64-x86_64-usbredir
        mingw-w64-x86_64-libtasn1
        mingw-w64-x86_64-nettle
        mingw-w64-x86_64-cyrus-sasl
        mingw-w64-x86_64-curl
        mingw-w64-x86_64-gnutls
        mingw-w64-x86_64-zstd"
  script:
    - C:\tools\msys64\usr\bin\bash.exe -lc "mkdir build"
    - C:\tools\msys64\usr\bin\bash.exe -lc "cd build && ../configure
      --python=python3 --ninja=ninja
      --target-list-exclude=i386-softmmu,arm-softmmu,ppc-softmmu,mips-softmmu"
    - C:\tools\msys64\usr\bin\bash.exe -lc "cd build && make -j$NUMBER_OF_PROCESSORS"
  test_script:
    - C:\tools\msys64\usr\bin\bash.exe -lc "cd build && make V=1 check"
